# Generated by Django 3.0.5 on 2020-05-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200429_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='room',
        ),
    ]
