# Generated by Django 3.0.5 on 2020-05-04 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=4096)),
                ('role', models.CharField(choices=[('MAN', 'Manager'), ('AN', 'Analyst'), ('DEV', 'Developer'), ('TEST', 'Tester')], max_length=50)),
                ('executor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Executor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
