# Generated by Django 3.0.5 on 2020-05-04 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_board_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.Team'),
        ),
    ]
