# Generated by Django 3.0.5 on 2020-05-04 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200429_2125'),
        ('task_manager', '0006_auto_20200504_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='team',
            new_name='teams',
        ),
        migrations.RemoveField(
            model_name='task',
            name='board',
        ),
        migrations.AddField(
            model_name='board',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Room'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 13, 44, 13, 981645)),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('AN', 'Analyzed'), ('IN_D', 'In developing'), ('TEST', 'Testing'), ('CHECK', 'Checking'), ('FIN', 'Finished')], max_length=5)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.Board')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.Process'),
        ),
    ]
