# Generated by Django 3.0.5 on 2020-05-04 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_auto_20200504_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='team',
            name='room',
        ),
        migrations.AddField(
            model_name='team',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager.Board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 15, 41, 26, 49366)),
        ),
    ]
