# Generated by Django 3.0.5 on 2020-05-04 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_auto_20200504_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 16, 57, 46, 345046)),
        ),
        migrations.AlterField(
            model_name='team',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='task_manager.Board'),
        ),
    ]
