# Generated by Django 3.0.5 on 2020-05-08 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bp_manager', '0001_initial'),
        ('task_manager', '0012_auto_20200505_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='board',
        ),
        migrations.RemoveField(
            model_name='team',
            name='board',
        ),
        migrations.RemoveField(
            model_name='team',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='team',
            name='workers',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 14, 13, 34, 57429)),
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bp_manager.Process'),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
