# Generated by Django 3.0.5 on 2020-05-08 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_customuser_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Board', max_length=50)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Team', max_length=50)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bp_manager.Board')),
                ('managers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to=settings.AUTH_USER_MODEL)),
                ('workers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('AN', 'Analyzed'), ('IN_D', 'In developing'), ('TEST', 'Testing'), ('CHECK', 'Checking'), ('FIN', 'Finished')], max_length=5)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bp_manager.Board')),
            ],
        ),
    ]
